#!/bin/ash
hosts=$(env | grep _TCP_ADDR | cut -d = -f 2)
ports=$(env | grep _TCP_PORT | cut -d = -f 2)
count=${COUNT:-30}  # number of seconds to wait

for host in $hosts; do

  set -- $ports
  port=$1
  success='false'

  echo -n "waiting for TCP connection to ${host}:${port} ..."
  for i in $(seq 1 ${count}); do
    if echo -n "\cD" | telnet ${host} ${port} 2>/dev/null; then
      success='true'
      break
    fi
    echo -n .
    sleep 1
  done

  echo ''
  if [ "${success}" = 'true' ]; then
    echo "port ${port} is accepting TCP connections"
  else
    echo "unable to reach ${host}:${port} over TCP"
    exit 1
  fi

  shift  # next port

done
